[package]
name = "mqtt-smarthome"
version = "0.3.2"
license = "MIT"
repository = "https://github.com/EdJoPaTo/mqtt-smarthome"
authors = ["EdJoPaTo <mqtt-smarthome-rust@edjopato.de>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "0.14"
tokio = { version = "1.0", features = ["sync"] }

[dev-dependencies]
float_eq = "1.0"
