[package]
name = "mqtt-smarthome"
version = "0.3.2"
license = "MIT"
repository = "https://github.com/EdJoPaTo/mqtt-smarthome"
authors = ["EdJoPaTo <mqtt-smarthome-rust@edjopato.de>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["tls"]
tls = ["rumqttc/use-rustls"]

[dependencies]
rumqttc = { version = "0.16", default-features = false }
tokio = { version = "1", features = ["sync"] }

[dev-dependencies]
float_eq = "1"
